### PR TITLE
Preserve query in the `link` action

### LINKED ISSUE #79: use:link does not pass query params to the next route
Whenever I use an anchor tag with a "use:link" attribute, the query params specified in the href attribute are not passed on.

`<a use:link href="/partners?roger=true">Foobar</a>`

Here the app routes to the '/partners' route correctly but the roger query param isn't available in location.search.

### PR DESCRIPTION
**Pull request by cibernox**
Closes #79 

This was super annoying and so easy to fix.

### CODE REVIEW

**Comment by cibernox** [comment]
Is there any feedback here? Is this project alive?

**Comment by EmilTholin** [comment]
Jesus Christ, "Is this project alive?". Do you think contributors feel like they want to help you/look at your issues/PRs with this attitude?

Other issues in this repository were resolved three days ago, this will be looked at when a contributor has time.

**Comment by cibernox** [comment]
Apologise if that came across the wrong way, i certainly wasn't my intention. 

I asked because there are quite a few svelte routers and I don't have a sense of which ones are actively being developed, specially with sapper having being official-ish and having its own router.

Again, my sincere apologies.

**Comment by rmanzano-TE** [comment]
Should also update the `links` action on [line 72](https://github.com/EmilTholin/svelte-routing/blob/master/src/actions.js#L72)

**Comment by EmilTholin** [comment]
Thank you for the fix @cibernox! This nice addition has been released in `1.4.1`.

**Pull request merged**
