### PR TITLE
Taking an initial stab at Svelte 3 support

### PR DESCRIPTION
**Pull request by jacwright**
Tested Route.html so far and seems to work. The rest is converted but untested.

### CODE REVIEW

**Comment by EmilTholin** [comment]
Hey @jacwright!

Sorry for the slow feedback on this PR. It looks really good!

I'm currently experimenting with a complete rewrite in a private repository that takes full advantage of all the new context features of `v3`, but the last missing piece of the puzzle [is not working yet](https://github.com/sveltejs/svelte/issues/2259).

If the experiment turns out to not be successful, your PR will be a solid base to build upon for `v3`.

**Comment by jacwright** [comment]
Looks like the last piece of the puzzle [isn't going to be resolved](https://github.com/sveltejs/svelte/issues/2259#issuecomment-477292138). 🙁 Do you have any other ideas?

**Comment by EmilTholin** [comment]
Yes, it's looking grim. I think it's best to wait until it's ruled out altogether.

**Comment by EmilTholin** [comment]
Thank you for taking an initial stab at it @jacwright and all the help in chat! I think it turned out well in the end.

**Pull request closed without merging**
